name: Deploy Prod (legacy)

on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to server
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          SERVER_USER_DEPLOYER: ${{ secrets.SERVER_USER_DEPLOYER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER_DEPLOYER@$SERVER_IP << 'EOF'
          cd /srv/sae5/sae5 || exit
          git pull origin main
          docker compose -f docker-compose.prod.yml pull
          docker compose -f docker-compose.prod.yml up -d --build
          EOF

      - name: Stop Test Server
        if: github.ref == 'refs/heads/main'
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          SERVER_USER_DEPLOYER: ${{ secrets.SERVER_USER_DEPLOYER }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $SERVER_USER_DEPLOYER@$SERVER_IP << 'EOF'
          cd /srv/sae5/sae5-test || exit
          docker compose -f docker-compose.test.yml down
          EOF
