name: Test ‚Üí Prod CI

on:
  pull_request:
    branches:
      - prod
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: üßπ Lint Code (Frontend + Backend)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # LINT FRONTEND
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ./front
        run: npm ci

      - name: Run ESLint
        working-directory: ./front
        run: npm run lint

      # LINT BACKEND
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        working-directory: ./back
        run: flake8 ./app

  build:
    name: üèóÔ∏è Build Docker Images
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_PROFILE: ${{ secrets.APP_PROFILE }}
      BACKEND_API_ADDRESS: ${{ secrets.BACKEND_API_ADDRESS }}
      MODEL_DIR: ${{ secrets.MODEL_DIR }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker images (prod)
        run: docker compose -f docker-compose.prod.yml build

  test:
    name: üß™ Run Tests (Frontend + Backend)
    runs-on: ubuntu-latest
    needs: build
    env:
      APP_NAME: ${{ secrets.APP_NAME }}
      APP_PROFILE: ${{ secrets.APP_PROFILE }}
      BACKEND_API_ADDRESS: ${{ secrets.BACKEND_API_ADDRESS }}
      MODEL_DIR: ${{ secrets.MODEL_DIR }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start services for testing
        run: docker compose -f docker-compose.prod.yml up -d

      # FRONT TESTS
      #- name: Set up Node.js
        #  uses: actions/setup-node@v4
        #with:
        #  node-version: 20
      #
      #- name: Run frontend tests
        #  working-directory: ./front
        #run: |
        #  npm ci
        #  npm test -- --watchAll=false

      # BACK TESTS
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./back
        run: pip install -r requirements.txt

      - name: Run backend tests
        working-directory: ./back
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Stop services
        if: always()
        run: docker compose -f docker-compose.prod.yml down
